FROM ghcr.io/graalvm/graalvm-ce:22.3.0 as builder
ARG TARGETARCH

WORKDIR /app
COPY . /app

RUN gu install native-image

RUN cd /app && ./sbt clean GraalVMNativeImage/packageBin


FROM oraclelinux:9-slim

WORKDIR /tmp

COPY --from=builder /app/target/graalvm-native-image/easyracer-server /easyracer-server

ENTRYPOINT ["/easyracer-server"]