FROM ghcr.io/graalvm/native-image-community:21 as builder
ARG TARGETARCH

WORKDIR /app
COPY . /app

RUN cd /app && ./sbt clean GraalVMNativeImage/packageBin


FROM oraclelinux:9-slim

WORKDIR /tmp

COPY --from=builder /app/target/graalvm-native-image/easyracer-server /easyracer-server

ENTRYPOINT ["/easyracer-server"]